"""Aegis on Telegram — the briefing, the remote control, and the approval tap.

WHY THIS IS AEGIS'S OWN BRIDGE AND NOT AN OPENCLAW CHANNEL
==========================================================
On 2026-09-22 OpenClaw was linked to WhatsApp through "Linked Devices", which
does not create a bot — it makes OpenClaw a **device on Murat's own account**.
It could therefore see and answer every conversation on it, and it replied to a
friend. The lesson is not "WhatsApp is bad"; it is that a channel where the
agent borrows a human's identity has no boundary to enforce.

A Telegram BOT has its own identity and its own chat. It can only ever see
messages sent directly to it, so there is no conversation it could wander into.

This module is deliberately NOT an OpenClaw plugin:

* it must work when OpenClaw is stopped (it was, for most of today);
* what Aegis sends about money should be generated by Aegis's own receipts, not
  by a general agent that might summarise them; and
* the allowlist has to be ours, enforced on OUR side of the wire.

THE ONE RULE
============
**`OWNER_CHAT_ID` or nothing.** Every send is addressed to exactly one chat, and
`send()` REFUSES when the owner id is unset rather than falling back to whoever
last spoke. A bridge that can be steered into a new recipient by an inbound
message is how the WhatsApp incident happened, and the fix is that the
destination is configuration, never message-derived.

Inbound is filtered the same way: a command from any other chat is logged,
answered with a refusal, and never executed. `/start` from a stranger does not
claim ownership — it says so.

WHAT IT IS FOR, BEYOND CHAT
===========================
1. **The daily brief.** NAV from the broker, session P&L, the ranked book,
   what changed since yesterday. The morning report already exists; this puts
   the first paragraph of it on his phone.
2. **Remote control.** Start and stop a simulation, read its state, from
   anywhere. The PC is the trading node and he is not always at it.
3. **The approval tap** — the one with real leverage. This programme has
   attended gates (seeding a lane, a spend above a cap, promoting a candidate
   to CAPITAL_CANDIDATE) that stall until Murat is at a keyboard. An approval
   request that reaches his phone turns "wait for the next session" into a tap,
   WITHOUT weakening the gate: the request still names what it wants, the
   evidence, and the worst case, and an unanswered request stays unapproved.
4. **Alarms that deserve interrupting for**: an ownership conflict on a broker
   account, a drawdown breach, a night that died without a receipt, CI red.

Everything here is text out and commands in. **It never places an order and it
never approves anything on its own** — it carries a request to a human and
carries the answer back.
"""

from __future__ import annotations

import json
import logging
import os
import re
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

logger = logging.getLogger(__name__)

from backend import config as _cfg

STATE_DIR = _cfg.OPTIMUS_LEDGER_DIR / "telegram"
OFFSET_PATH = STATE_DIR / "update_offset.json"
OUTBOX_PATH = STATE_DIR / "outbox.jsonl"
INBOX_PATH = STATE_DIR / "inbox.jsonl"
APPROVALS_PATH = STATE_DIR / "approvals.jsonl"

API = "https://api.telegram.org"
TOKEN_ENV = "TELEGRAM_BOT_TOKEN"
OWNER_ENV = "TELEGRAM_OWNER_CHAT_ID"

#: Telegram rejects messages over 4096 characters; long briefs are split.
MAX_LEN = 3900


class TelegramRefused(RuntimeError):
    """The bridge will not send. Never swallowed into a silent no-op."""


def _token() -> str:
    t = os.environ.get(TOKEN_ENV)
    if not t:
        raise TelegramRefused(
            f"REFUSED: {TOKEN_ENV} is not set. Create a bot with @BotFather and "
            f"put its token in .env.")
    return t


def owner_chat_id() -> str | None:
    v = (os.environ.get(OWNER_ENV) or "").strip()
    return v or None


def _call(method: str, payload: dict | None = None, *, timeout: float = 30.0) -> Any:
    url = f"{API}/bot{_token()}/{method}"
    data = json.dumps(payload or {}).encode()
    req = urllib.request.Request(
        url, data=data, headers={"Content-Type": "application/json"}, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=timeout) as fh:   # noqa: S310 allowlisted host
            body = json.loads(fh.read())
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode(errors="replace")[:300]
        raise TelegramRefused(f"{method} -> HTTP {exc.code}: {detail}") from exc
    if not body.get("ok"):
        raise TelegramRefused(f"{method} -> {body}")
    return body.get("result")


def me() -> dict:
    return _call("getMe")


# ─────────────────────────────── redaction ──────────────────────────────────
#
# G-fix, adjudication row 7 (reviewer G, SAFETY): `call_named` put `str(e)[:300]`
# into `error`, `/ask` `/deep` `/compare` sent it to Telegram, and `poll` sent any
# handler exception's text. A provider that echoes a key in a 401 body, or a
# traceback that prints a path or a `.env` line, would leave the machine. Every
# outbound text now passes `redact()` inside `send()` -- one choke point, so no
# handler can forget -- and `poll` redacts the exception text before building
# the reply as well.

REDACTED = "<redacted>"

_SECRET_AFTER_WORD = re.compile(
    r"(?i)((?:api[_-]?)?(?:key|token|secret)\w*[\s\"':=]{0,6}(?:bearer\s+)?)"
    r"[A-Za-z0-9_\-]{20,}")
_BEARER = re.compile(r"(?i)(bearer\s+)[A-Za-z0-9_\-\.=]{12,}")
_PREFIXED = re.compile(r"\b(?:sk|nvapi|pk|rk|ghp|xox[abpr]|APCA|PK)[-_][A-Za-z0-9_\-]{12,}")
_ENV_LINE = re.compile(r"(?m)^(\s*(?:export\s+)?[A-Z][A-Z0-9_]{2,}\s*=\s*)\S.*$")
_ENV_INLINE = re.compile(
    r"\b([A-Z][A-Z0-9_]*(?:KEY|TOKEN|SECRET|PASSWORD|PASS|PWD)[A-Z0-9_]*\s*=\s*)[^\s,;'\"]+")


def _home_pattern() -> "re.Pattern[str] | None":
    try:
        parts = [x for x in re.split(r"[\\/]+", str(Path.home())) if x]
    except (RuntimeError, OSError):
        return None
    if not parts:
        return None
    # C:\Users\name, C:/Users/name, C:\\Users\\name (a repr) all match
    return re.compile(r"[\\/]*".join(re.escape(x) for x in parts) + r"(?=[\\/]|\b)",
                      re.IGNORECASE)


def redact(text: Any) -> str:
    """Strip what must never reach a third party from outbound text.

    * paths under the user's home -> `~`
    * a run of 20+ `[A-Za-z0-9_-]` after `key` / `token` / `secret`
      (case-insensitive, e.g. `api_key='...'`, `NVIDIA_API_KEY=...`)
    * `Bearer ...`, and the house key prefixes (`sk-`, `nvapi-`, `APCA...`)
    * `.env`-shaped lines (`NAME=value`) -> `NAME=<redacted>`
    """
    t = "" if text is None else str(text)
    hp = _home_pattern()
    if hp is not None:
        t = hp.sub("~", t)
    t = _ENV_LINE.sub(lambda m: m.group(1) + REDACTED, t)
    t = _ENV_INLINE.sub(lambda m: m.group(1) + REDACTED, t)
    t = _BEARER.sub(lambda m: m.group(1) + REDACTED, t)
    t = _SECRET_AFTER_WORD.sub(lambda m: m.group(1) + REDACTED, t)
    t = _PREFIXED.sub(REDACTED, t)
    return t


# ──────────────────────────────── outbound ──────────────────────────────────

def send(text: str, *, chat_id: str | None = None, markdown: bool = True,
         tag: str = "message") -> list[dict]:
    """Send to the OWNER. Refuses when no owner is configured.

    `chat_id` exists for `/start`, where the only way to learn the owner's id is
    to answer the message that carried it. It is never used to redirect a brief
    or an alert: those always resolve `owner_chat_id()`.
    """
    target = chat_id or owner_chat_id()
    if not target:
        raise TelegramRefused(
            f"REFUSED: no owner chat id. Set {OWNER_ENV} in .env, or send /start "
            f"to the bot once and `claim_owner()` will capture it. This bridge "
            f"does not reply to whoever spoke last — the destination is "
            f"configuration, not message-derived.")
    if tag in BRIEF_TAGS:
        text = _health_head() + text
    text = redact(text)
    out = []
    for chunk in _split(text):
        payload = {"chat_id": target, "text": chunk,
                   "disable_web_page_preview": True}
        if markdown:
            payload["parse_mode"] = "Markdown"
        try:
            out.append(_call("sendMessage", payload))
        except TelegramRefused:
            payload.pop("parse_mode", None)      # unbalanced * or _ in a receipt
            out.append(_call("sendMessage", payload))
    _append(OUTBOX_PATH, {"t": _now(), "tag": tag, "chat_id": target,
                          "chars": len(text)})
    return out


#: Sends that are the phone's front page: the probes' DEAD/STALE rows go FIRST.
BRIEF_TAGS = ("brief", "cmd:brief")


def _health_head() -> str:
    """DEAD/STALE subsystem rows, one line each, above the brief. Never raises:
    a health read that fails must not cost the brief itself."""
    try:
        from backend.services.system_health import non_alive_lines
        lines = non_alive_lines(limit=8)
    except Exception as exc:                                       # noqa: BLE001
        lines = [f"_subsystems: CANNOT DETERMINE ({type(exc).__name__})_"]
    return "\n".join(lines) + "\n\n"


def _split(text: str) -> list[str]:
    if len(text) <= MAX_LEN:
        return [text]
    parts, cur = [], []
    n = 0
    for line in text.splitlines(keepends=True):
        if n + len(line) > MAX_LEN and cur:
            parts.append("".join(cur)); cur, n = [], 0
        cur.append(line); n += len(line)
    if cur:
        parts.append("".join(cur))
    return parts


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _append(path: Path, row: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(row, default=str) + "\n")


# ──────────────────────────────── inbound ───────────────────────────────────

def _offset() -> int:
    d = None
    if OFFSET_PATH.exists():
        try:
            d = json.loads(OFFSET_PATH.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            d = None
    return int((d or {}).get("offset", 0))


def _set_offset(v: int) -> None:
    OFFSET_PATH.parent.mkdir(parents=True, exist_ok=True)
    OFFSET_PATH.write_text(json.dumps({"offset": v, "at": _now()}), encoding="utf-8")


def updates(*, timeout: int = 0) -> list[dict]:
    """New messages since the last read. Advances the offset so none repeat."""
    off = _offset()
    res = _call("getUpdates",
                {"offset": off + 1 if off else None, "timeout": timeout,
                 "allowed_updates": ["message"]},
                timeout=timeout + 25) or []
    if res:
        _set_offset(max(u["update_id"] for u in res))
    return res


def claim_owner() -> dict:
    """Capture the owner's chat id from the FIRST /start, once.

    Deliberately one-shot: once `TELEGRAM_OWNER_CHAT_ID` is set, a later /start
    from anyone cannot move it. Ownership is claimed by the first person with
    the bot's link and then frozen; changing it is a .env edit by a human.
    """
    if owner_chat_id():
        return {"claimed": False, "why": "an owner is already configured",
                "owner": owner_chat_id()}
    for u in updates():
        msg = u.get("message") or {}
        chat = msg.get("chat") or {}
        if str(msg.get("text", "")).strip().lower().startswith("/start"):
            cid = str(chat.get("id"))
            _persist_owner(cid)
            who = chat.get("username") or chat.get("first_name") or "?"
            send(f"*AEGIS connected.*\nOwner set to `{cid}` ({who}).\n"
                 f"This bot answers only this chat.\n\nSend /help for what it can do.",
                 chat_id=cid, tag="claim")
            return {"claimed": True, "owner": cid, "username": who}
    return {"claimed": False, "why": "no /start seen yet — message the bot first"}


def _persist_owner(cid: str) -> None:
    os.environ[OWNER_ENV] = cid
    env = Path(_cfg.PROJECT_ROOT) / ".env" if hasattr(_cfg, "PROJECT_ROOT") else Path(".env")
    try:
        lines = env.read_text(encoding="utf-8").splitlines()
        out, found = [], False
        for ln in lines:
            if ln.startswith(f"{OWNER_ENV}="):
                out.append(f"{OWNER_ENV}={cid}"); found = True
            else:
                out.append(ln)
        if not found:
            out.append(f"{OWNER_ENV}={cid}")
        env.write_text("\n".join(out) + "\n", encoding="utf-8")
    except OSError as exc:
        logger.warning("telegram_bridge: could not persist owner id: %s", exc)


def poll(handlers: dict[str, Callable[[list[str], dict], str]] | None = None) -> list[dict]:
    """Read new messages and run the matching command. Owner only.

    A message from any other chat is recorded and answered with a refusal that
    names why, so a stranger learns nothing about the account and the owner can
    see in `inbox.jsonl` that someone tried.
    """
    owner = owner_chat_id()
    acted = []
    for u in updates():
        msg = u.get("message") or {}
        cid = str((msg.get("chat") or {}).get("id"))
        text = (msg.get("text") or "").strip()
        row = {"t": _now(), "chat_id": cid, "text": text[:400],
               "from": (msg.get("from") or {}).get("username")}
        if owner and cid != owner:
            row["refused"] = "not the owner chat"
            _append(INBOX_PATH, row)
            try:
                send("This bot is private and answers only its owner.",
                     chat_id=cid, markdown=False, tag="refusal")
            except TelegramRefused:
                pass
            continue
        _append(INBOX_PATH, row)
        if not text.startswith("/"):
            continue
        parts = text.split()
        cmd = parts[0].lstrip("/").split("@")[0].lower()
        fn = (handlers or {}).get(cmd)
        if fn is None:
            send(f"Unknown command `/{cmd}`. Send /help.", tag="unknown")
            continue
        try:
            reply = fn(parts[1:], msg)
        except Exception as exc:                                   # noqa: BLE001
            reply = f"`/{cmd}` failed: `{type(exc).__name__}: {redact(exc)}`"
            logger.exception("telegram command %s failed", cmd)
        if reply:
            send(reply, tag=f"cmd:{cmd}")
        acted.append({"cmd": cmd, "args": parts[1:]})
    return acted


# ─────────────────────────────── approvals ──────────────────────────────────

def request_approval(*, what: str, why: str, worst_case: str,
                     evidence: Any, request_id: str | None = None) -> dict:
    """Carry an attended decision to Murat's phone. It does NOT approve anything.

    The gate is unchanged: what is asked for, the evidence behind it and the
    worst case in dollars all travel with the request, and an unanswered request
    stays unapproved. What changes is latency — an attended gate used to wait
    for him to be at a keyboard.
    """
    rid = request_id or f"AP{datetime.now(timezone.utc):%Y%m%d%H%M%S}"
    row = {"t": _now(), "id": rid, "what": what, "why": why,
           "worst_case": worst_case, "evidence": evidence, "state": "PENDING"}
    _append(APPROVALS_PATH, row)
    send(f"*APPROVAL NEEDED* `{rid}`\n\n"
         f"*What:* {what}\n*Why:* {why}\n*Worst case:* {worst_case}\n\n"
         f"Reply `/approve {rid}` or `/deny {rid}`.\n"
         f"_Unanswered means NOT approved._", tag="approval")
    return row


def resolve_approval(rid: str, *, approved: bool, by: str = "telegram") -> dict:
    rows = pending_approvals(include_all=True)
    match = next((r for r in rows if r["id"] == rid and r["state"] == "PENDING"), None)
    if not match:
        return {"ok": False, "why": f"no PENDING approval with id {rid}"}
    row = {**match, "state": "APPROVED" if approved else "DENIED",
           "resolved": _now(), "by": by}
    _append(APPROVALS_PATH, row)
    return {"ok": True, **row}


def pending_approvals(*, include_all: bool = False) -> list[dict]:
    """Latest state per request id, so a resolution supersedes its request."""
    if not APPROVALS_PATH.exists():
        return []
    latest: dict[str, dict] = {}
    for line in APPROVALS_PATH.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        r = json.loads(line)
        latest[r["id"]] = r
    rows = list(latest.values())
    return rows if include_all else [r for r in rows if r["state"] == "PENDING"]


def status() -> dict:
    """Is the bridge usable, and who does it answer to?"""
    out: dict[str, Any] = {"token_present": bool(os.environ.get(TOKEN_ENV)),
                           "owner_chat_id": owner_chat_id()}
    if not out["token_present"]:
        out["state"] = "NOT CONFIGURED: no TELEGRAM_BOT_TOKEN"
        return out
    try:
        b = me()
        out["bot"] = {"username": b.get("username"), "id": b.get("id")}
        out["state"] = ("READY" if out["owner_chat_id"]
                        else "AWAITING /start — no owner chat id yet")
    except TelegramRefused as exc:
        out["state"] = f"UNREACHABLE: {exc}"
    out["pending_approvals"] = len(pending_approvals())
    return out
