"""
Aegis Finance — Portfolio Intelligence Database
=================================================

Raw SQLite with WAL mode for the portfolio intelligence subsystem.
Forward-only schema versioning (no Alembic — overkill for 6 tables).

The rest of Aegis is stateless. This module adds persistence ONLY
for paper-portfolio state, trade log, audit log, and personal decisions.

Usage:
    from backend.db import init_db, get_connection, DB_PATH
"""

import hashlib
import json
import logging
import sqlite3
import threading
from pathlib import Path

from backend.config import BACKEND_DIR, DATA_DIR

logger = logging.getLogger(__name__)

# DATA_DIR is env-configurable (AEGIS_DATA_DIR) so Railway can persist the DB on
# a volume WITHOUT shadowing the baked-in paper_portfolios.yaml, which stays under
# BACKEND_DIR/data (immutable). See config.DATA_DIR for the volume-mount contract.
DB_PATH = DATA_DIR / "aegis_pi.db"

_write_lock = threading.Lock()

CURRENT_SCHEMA_VERSION = 5

_SCHEMA_V1 = """
CREATE TABLE IF NOT EXISTS _schema_version (
    version INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS paper_portfolios (
    id TEXT PRIMARY KEY,                 -- 'conservative', 'balanced', 'aggressive'
    inception_date TEXT NOT NULL,        -- ISO date
    inception_value REAL NOT NULL,       -- 100000.0
    config_version TEXT NOT NULL         -- SHA-256 of paper_portfolios.yaml at creation
);

CREATE TABLE IF NOT EXISTS paper_positions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    portfolio_id TEXT NOT NULL REFERENCES paper_portfolios(id),
    ticker TEXT NOT NULL,
    shares REAL NOT NULL,
    cost_basis REAL NOT NULL,
    opened_at TEXT NOT NULL,
    closed_at TEXT                       -- NULL if still open
);

CREATE TABLE IF NOT EXISTS paper_trades (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    portfolio_id TEXT NOT NULL REFERENCES paper_portfolios(id),
    ticker TEXT NOT NULL,
    side TEXT NOT NULL CHECK(side IN ('buy', 'sell')),
    shares REAL NOT NULL,
    price REAL NOT NULL,
    transaction_cost REAL NOT NULL,
    slippage REAL NOT NULL,
    executed_at TEXT NOT NULL,
    rebalance_event_id INTEGER REFERENCES rebalance_events(id)
);

CREATE TABLE IF NOT EXISTS rebalance_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    portfolio_id TEXT NOT NULL REFERENCES paper_portfolios(id),
    triggered_at TEXT NOT NULL,
    trigger_reason TEXT NOT NULL,        -- 'monthly', 'drift', 'crash_overlay', 'weekly_aggressive'
    pre_weights TEXT NOT NULL,           -- JSON dict of ticker→weight before rebalance
    post_weights TEXT NOT NULL,          -- JSON dict of ticker→weight after rebalance
    crash_prob_3m REAL,
    regime TEXT,
    explanation TEXT NOT NULL            -- human-readable, generated by rules.py
);

CREATE TABLE IF NOT EXISTS audit_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TEXT NOT NULL,
    portfolio_id TEXT,
    event_type TEXT NOT NULL,            -- 'rebalance_check', 'flag_raised', 'crash_overlay_armed', 'no_rebalance'
    payload TEXT NOT NULL                -- JSON blob
);

CREATE TABLE IF NOT EXISTS personal_decisions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TEXT NOT NULL,
    ticker TEXT NOT NULL,
    action TEXT NOT NULL CHECK(action IN ('enter', 'add', 'trim', 'exit')),
    shares_delta REAL NOT NULL,
    price REAL NOT NULL,
    rationale TEXT NOT NULL,             -- min 50 chars, enforced in application layer
    thesis_tags TEXT NOT NULL DEFAULT '[]',  -- JSON list of strings
    conviction INTEGER NOT NULL CHECK(conviction BETWEEN 1 AND 5),
    target_price REAL,
    stop_price REAL,
    planned_exit_trigger TEXT,
    catalyst_dates TEXT DEFAULT '[]',    -- JSON list of ISO dates
    portfolio_snapshot TEXT NOT NULL,    -- JSON full state at decision time
    amends_id INTEGER REFERENCES personal_decisions(id)  -- NULL if original, FK if amendment
);

-- Immutability enforcement: personal decisions cannot be updated or deleted.
-- Edits create new rows via amends_id. This prevents retroactive narrative
-- editing — critical for honest skill measurement (SPEC §9).
CREATE TRIGGER IF NOT EXISTS prevent_decision_update
    BEFORE UPDATE ON personal_decisions
    BEGIN
        SELECT RAISE(ABORT, 'personal_decisions is immutable — create a new row with amends_id instead');
    END;

CREATE TRIGGER IF NOT EXISTS prevent_decision_delete
    BEFORE DELETE ON personal_decisions
    BEGIN
        SELECT RAISE(ABORT, 'personal_decisions is immutable — rows cannot be deleted');
    END;

CREATE TABLE IF NOT EXISTS decision_outcomes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    decision_id INTEGER NOT NULL REFERENCES personal_decisions(id),
    evaluated_at TEXT NOT NULL,
    realized_return REAL NOT NULL,
    benchmark_return REAL NOT NULL,
    attr_beta REAL NOT NULL,
    attr_sector REAL NOT NULL,
    attr_selection REAL NOT NULL,
    attr_timing REAL NOT NULL,
    skill_residual REAL NOT NULL
);
"""


def _compute_config_hash(yaml_path: Path) -> str:
    """SHA-256 of the parsed YAML config (not raw bytes).

    Hashing parsed config means whitespace/comment changes don't
    invalidate the version — only meaningful value changes do.
    """
    if not yaml_path.exists():
        return "no-config"
    try:
        import yaml
        with open(yaml_path, "r") as f:
            parsed = yaml.safe_load(f) or {}
        normalized = json.dumps(parsed, sort_keys=True, default=str)
        return hashlib.sha256(normalized.encode()).hexdigest()[:16]
    except Exception:
        return hashlib.sha256(yaml_path.read_bytes()).hexdigest()[:16]


def _run_migrations(conn: sqlite3.Connection, from_version: int, to_version: int) -> None:
    """Run forward-only schema migrations.

    Each migration is a function that takes a connection and applies
    ALTER TABLE / CREATE TABLE / CREATE INDEX statements.
    New migrations go at the bottom with the next version number.
    """
    if from_version < 2:
        # v2: persistent walk-forward replay cache. Hashes of universe + rules
        # let us auto-invalidate when paper_portfolios.yaml changes;
        # market_data_date gives us natural daily rollover.
        conn.executescript("""
            CREATE TABLE IF NOT EXISTS replay_cache (
                lane_id TEXT NOT NULL,
                universe_hash TEXT NOT NULL,
                rules_hash TEXT NOT NULL,
                market_data_date TEXT NOT NULL,
                computed_at TEXT NOT NULL,
                result_json TEXT NOT NULL,
                PRIMARY KEY (lane_id, universe_hash, rules_hash, market_data_date)
            );
            CREATE INDEX IF NOT EXISTS idx_replay_cache_lane
                ON replay_cache (lane_id, computed_at DESC);
        """)

    if from_version < 3:
        # v3: (a) paper_nav — daily mark-to-market NAV for the live forward track
        # record, segmented by config_version so optimization/rule changes that
        # land as versioned config edits don't contaminate the prior segment.
        # (b) rule_experiments — the Aegis-OWNED trial registry for the guarded
        # rule-evolution loop. DSR/PBO must deflate against the CUMULATIVE trial
        # count across ALL runs (read from this table), not per-batch, or the
        # loop slowly overfits. Optimus may ingest this as corpus; it never owns it.
        conn.executescript("""
            CREATE TABLE IF NOT EXISTS paper_nav (
                portfolio_id TEXT NOT NULL REFERENCES paper_portfolios(id),
                date TEXT NOT NULL,              -- ISO date of the NAV mark
                nav REAL NOT NULL,               -- mark-to-market portfolio value
                config_version TEXT NOT NULL,    -- SHA of config producing this NAV
                computed_at TEXT NOT NULL,
                PRIMARY KEY (portfolio_id, date)
            );
            CREATE INDEX IF NOT EXISTS idx_paper_nav_lane
                ON paper_nav (portfolio_id, date);

            CREATE TABLE IF NOT EXISTS rule_experiments (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                created_at TEXT NOT NULL,
                config_version TEXT NOT NULL,
                lane_id TEXT,
                param TEXT NOT NULL,             -- rule param tested (e.g. drift threshold)
                old_value TEXT,                  -- JSON
                new_value TEXT,                  -- JSON
                observed_sharpe REAL,
                n_obs INTEGER,
                batch_trials INTEGER NOT NULL,   -- candidates in this batch
                cumulative_trials INTEGER NOT NULL,  -- total trials AT this point
                dsr REAL,                        -- deflated against cumulative_trials
                pbo REAL,
                verdict TEXT NOT NULL,           -- 'adopted' | 'rejected'
                notes TEXT
            );
            CREATE INDEX IF NOT EXISTS idx_rule_experiments_created
                ON rule_experiments (created_at DESC);
        """)

    if from_version < 4:
        # v4: rebalance_events carries the config_version that produced it, so
        # a versioned config change (Step #2 v1→v2) stamps its segment boundary
        # on the event itself, not only on subsequent paper_nav rows.
        # Additive column only — historical rows keep NULL (pre-v4 events).
        conn.executescript("""
            ALTER TABLE rebalance_events ADD COLUMN config_version TEXT;
        """)

    if from_version < 5:
        # v5: rule_experiments carries the participation-ratio effective trial
        # count (N_eff) alongside the raw cumulative count. REPORTED, NOT gating
        # — the adoption guard still deflates against the raw count (a strictness
        # floor); N_eff is the "estimated independent-trials" view for audit.
        # Additive column only — historical rows keep NULL. Guarded: rule_experiments
        # was created in the <3 block, so skip cleanly if a db never had it, and
        # stay idempotent if the column is already present.
        has_table = conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name='rule_experiments'"
        ).fetchone()
        if has_table:
            cols = [r[1] for r in conn.execute(
                "PRAGMA table_info(rule_experiments)"
            ).fetchall()]
            if "effective_trials" not in cols:
                conn.execute(
                    "ALTER TABLE rule_experiments ADD COLUMN effective_trials REAL"
                )


def init_db(db_path: Path | None = None) -> None:
    """Create tables and run forward-only migrations.

    Safe to call multiple times — uses CREATE TABLE IF NOT EXISTS.
    """
    path = db_path or DB_PATH
    path.parent.mkdir(parents=True, exist_ok=True)

    conn = sqlite3.connect(str(path))
    try:
        conn.execute("PRAGMA journal_mode=WAL")
        conn.execute("PRAGMA foreign_keys=ON")

        conn.executescript(_SCHEMA_V1)

        row = conn.execute("SELECT MAX(version) FROM _schema_version").fetchone()
        current = row[0] if row[0] is not None else 0

        if current < CURRENT_SCHEMA_VERSION:
            _run_migrations(conn, current, CURRENT_SCHEMA_VERSION)
            conn.execute(
                "INSERT INTO _schema_version (version) VALUES (?)",
                (CURRENT_SCHEMA_VERSION,),
            )
            conn.commit()
            logger.info("Database initialized at schema version %d: %s", CURRENT_SCHEMA_VERSION, path)
        else:
            logger.debug("Database already at schema version %d", current)
    finally:
        conn.close()


def get_connection(db_path: Path | None = None) -> sqlite3.Connection:
    """Get a SQLite connection with standard pragmas.

    Callers are responsible for closing. Use as context manager:
        with get_connection() as conn:
            conn.execute(...)
    """
    path = db_path or DB_PATH
    conn = sqlite3.connect(str(path))
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    conn.row_factory = sqlite3.Row
    return conn


def get_config_hash() -> str:
    """Hash of the current paper_portfolios.yaml."""
    return _compute_config_hash(BACKEND_DIR / "data" / "paper_portfolios.yaml")


def insert_rebalance_event(
    conn: sqlite3.Connection,
    portfolio_id: str,
    triggered_at: str,
    trigger_reason: str,
    pre_weights: dict,
    post_weights: dict,
    crash_prob_3m: float | None,
    regime: str | None,
    explanation: str,
    config_version: str | None = None,
) -> int:
    """Insert a rebalance event. Returns the row id.

    config_version stamps which config produced the event (v4+); pass
    get_config_hash() from live paths so segment boundaries are auditable
    on the event itself.
    """
    with _write_lock:
        cursor = conn.execute(
            """INSERT INTO rebalance_events
               (portfolio_id, triggered_at, trigger_reason, pre_weights, post_weights,
                crash_prob_3m, regime, explanation, config_version)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                portfolio_id,
                triggered_at,
                trigger_reason,
                json.dumps(pre_weights),
                json.dumps(post_weights),
                crash_prob_3m,
                regime,
                explanation,
                config_version,
            ),
        )
        conn.commit()
        return cursor.lastrowid


def insert_audit_log(
    conn: sqlite3.Connection,
    timestamp: str,
    portfolio_id: str | None,
    event_type: str,
    payload: dict,
) -> int:
    """Insert an audit log entry. Returns the row id."""
    with _write_lock:
        cursor = conn.execute(
            """INSERT INTO audit_log (timestamp, portfolio_id, event_type, payload)
               VALUES (?, ?, ?, ?)""",
            (timestamp, portfolio_id, event_type, json.dumps(payload)),
        )
        conn.commit()
        return cursor.lastrowid


def _hash_dict(d: dict | list | None) -> str:
    """Stable SHA-256 of a JSON-serializable structure (sorted keys)."""
    if not d:
        return "empty"
    return hashlib.sha256(
        json.dumps(d, sort_keys=True, default=str).encode()
    ).hexdigest()[:16]


def compute_universe_hash() -> str:
    """Hash of paper_portfolios.universe (changes when ticker universe changes)."""
    from backend.config import paper_portfolios
    return _hash_dict(paper_portfolios.get("universe"))


def compute_rules_hash(lane_id: str) -> str:
    """Hash of a single lane's rule config (changes when thresholds/weights change).

    paper_portfolios.yaml stores each lane as a top-level key alongside 'universe'.
    """
    from backend.config import paper_portfolios
    lane_cfg = paper_portfolios.get(lane_id)
    return _hash_dict(lane_cfg)


def get_cached_replay(
    lane_id: str,
    universe_hash: str,
    rules_hash: str,
    market_data_date: str,
) -> str | None:
    """Return cached result_json string or None on miss."""
    conn = get_connection()
    try:
        row = conn.execute(
            """SELECT result_json FROM replay_cache
               WHERE lane_id = ? AND universe_hash = ? AND rules_hash = ?
                 AND market_data_date = ?""",
            (lane_id, universe_hash, rules_hash, market_data_date),
        ).fetchone()
        return row["result_json"] if row else None
    finally:
        conn.close()


def save_cached_replay(
    lane_id: str,
    universe_hash: str,
    rules_hash: str,
    market_data_date: str,
    result_json: str,
) -> None:
    """Upsert a cache entry. Last writer wins for the same key."""
    from datetime import datetime as _dt
    with _write_lock:
        conn = get_connection()
        try:
            conn.execute(
                """INSERT OR REPLACE INTO replay_cache
                   (lane_id, universe_hash, rules_hash, market_data_date,
                    computed_at, result_json)
                   VALUES (?, ?, ?, ?, ?, ?)""",
                (
                    lane_id,
                    universe_hash,
                    rules_hash,
                    market_data_date,
                    _dt.utcnow().isoformat(),
                    result_json,
                ),
            )
            conn.commit()
        finally:
            conn.close()


def invalidate_replay_cache(lane_id: str | None = None) -> int:
    """Drop cache rows. lane_id=None clears everything. Returns rows deleted."""
    with _write_lock:
        conn = get_connection()
        try:
            if lane_id is None:
                cursor = conn.execute("DELETE FROM replay_cache")
            else:
                cursor = conn.execute(
                    "DELETE FROM replay_cache WHERE lane_id = ?", (lane_id,)
                )
            conn.commit()
            return cursor.rowcount
        finally:
            conn.close()


def get_latest_cached_replay(lane_id: str) -> tuple[str, str] | None:
    """Most recent cache row for a lane regardless of hash (for stale-fallback).

    Returns (result_json, computed_at) or None.
    """
    conn = get_connection()
    try:
        row = conn.execute(
            """SELECT result_json, computed_at FROM replay_cache
               WHERE lane_id = ? ORDER BY computed_at DESC LIMIT 1""",
            (lane_id,),
        ).fetchone()
        if not row:
            return None
        return (row["result_json"], row["computed_at"])
    finally:
        conn.close()


def insert_nav(
    conn: sqlite3.Connection,
    portfolio_id: str,
    nav_date: str,
    nav: float,
    config_version: str,
    computed_at: str,
) -> None:
    """Upsert a daily mark-to-market NAV point (last writer wins per date)."""
    with _write_lock:
        conn.execute(
            """INSERT OR REPLACE INTO paper_nav
               (portfolio_id, date, nav, config_version, computed_at)
               VALUES (?, ?, ?, ?, ?)""",
            (portfolio_id, nav_date, nav, config_version, computed_at),
        )
        conn.commit()


def get_nav_series(
    conn: sqlite3.Connection,
    portfolio_id: str,
    config_version: str | None = None,
) -> list[dict]:
    """Return [{date, nav, config_version}] ordered by date.

    Pass config_version to fetch only one track-record segment (so a versioned
    rule/optimization change starts a clean segment instead of contaminating
    the prior one).
    """
    if config_version is None:
        rows = conn.execute(
            "SELECT date, nav, config_version FROM paper_nav "
            "WHERE portfolio_id = ? ORDER BY date",
            (portfolio_id,),
        ).fetchall()
    else:
        rows = conn.execute(
            "SELECT date, nav, config_version FROM paper_nav "
            "WHERE portfolio_id = ? AND config_version = ? ORDER BY date",
            (portfolio_id, config_version),
        ).fetchall()
    return [{"date": r["date"], "nav": r["nav"],
             "config_version": r["config_version"]} for r in rows]


def count_cumulative_trials(conn: sqlite3.Connection) -> int:
    """Total rule-evolution trials EVER recorded.

    This is the multiple-testing count the DSR/PBO guards must deflate against —
    cumulative across all loop runs, not per-batch. See record_trial /
    experiment_registry for the guarded acceptance logic.
    """
    row = conn.execute("SELECT COUNT(*) AS n FROM rule_experiments").fetchone()
    return int(row["n"]) if row else 0


def insert_experiment(
    conn: sqlite3.Connection,
    created_at: str,
    config_version: str,
    param: str,
    batch_trials: int,
    cumulative_trials: int,
    verdict: str,
    *,
    lane_id: str | None = None,
    old_value=None,
    new_value=None,
    observed_sharpe: float | None = None,
    n_obs: int | None = None,
    dsr: float | None = None,
    pbo: float | None = None,
    effective_trials: float | None = None,
    notes: str | None = None,
) -> int:
    """Record one rule-evolution trial in the registry. Returns the row id."""
    with _write_lock:
        cursor = conn.execute(
            """INSERT INTO rule_experiments
               (created_at, config_version, lane_id, param, old_value, new_value,
                observed_sharpe, n_obs, batch_trials, cumulative_trials,
                dsr, pbo, effective_trials, verdict, notes)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                created_at, config_version, lane_id, param,
                json.dumps(old_value) if old_value is not None else None,
                json.dumps(new_value) if new_value is not None else None,
                observed_sharpe, n_obs, batch_trials, cumulative_trials,
                dsr, pbo, effective_trials, verdict, notes,
            ),
        )
        conn.commit()
        return cursor.lastrowid


def insert_personal_decision(
    conn: sqlite3.Connection,
    timestamp: str,
    ticker: str,
    action: str,
    shares_delta: float,
    price: float,
    rationale: str,
    thesis_tags: list[str],
    conviction: int,
    portfolio_snapshot: dict,
    target_price: float | None = None,
    stop_price: float | None = None,
    planned_exit_trigger: str | None = None,
    catalyst_dates: list[str] | None = None,
    amends_id: int | None = None,
) -> int:
    """Insert a personal decision. Immutable — edits create new rows via amends_id.

    Raises ValueError if rationale is too short.
    """
    if len(rationale) < 50:
        raise ValueError(f"Rationale must be >= 50 characters (got {len(rationale)})")
    if conviction < 1 or conviction > 5:
        raise ValueError(f"Conviction must be 1-5 (got {conviction})")
    if action not in ("enter", "add", "trim", "exit"):
        raise ValueError(f"Action must be enter/add/trim/exit (got {action})")

    with _write_lock:
        cursor = conn.execute(
            """INSERT INTO personal_decisions
               (timestamp, ticker, action, shares_delta, price, rationale,
                thesis_tags, conviction, target_price, stop_price,
                planned_exit_trigger, catalyst_dates, portfolio_snapshot, amends_id)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                timestamp,
                ticker,
                action,
                shares_delta,
                price,
                rationale,
                json.dumps(thesis_tags),
                conviction,
                target_price,
                stop_price,
                planned_exit_trigger,
                json.dumps(catalyst_dates or []),
                json.dumps(portfolio_snapshot),
                amends_id,
            ),
        )
        conn.commit()
        return cursor.lastrowid
