"""5c T2 -- the curve wired into `Policy`, `CostModel` and the farm's replay.

The two tests that matter most here are the boring ones: that adding a field
to two frozen, hashed records changed NO existing identity, and that the flat
path still produces the number it produced yesterday. Everything else in this
file is a consequence of those two holding.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

from backend.services.portfolio_farm import replay
from backend.services.portfolio_farm.panel import Panel
from backend.services.portfolio_farm.policy import Policy, PolicyError
from backend.strategy.contract import (Benchmark, Construction, CostModel,
                                       HoldRule, LossBudget, Objective, Signal,
                                       Sizing, Strategy, Universe)

T = 420


def _strategy(**kw) -> Strategy:
    base = dict(
        strategy_id="test:book", title="a book", universe=Universe(name="u"),
        signal=Signal(name="mom_12_1"), construction=Construction(),
        hold=HoldRule(), sizing=Sizing(), costs=CostModel(),
        benchmark=Benchmark(), objective=Objective(),
        loss_budget=LossBudget(positions_judged=20, expected_losers=8))
    base.update(kw)
    return Strategy(**base)


def _panel(n_names: int = 8, ret: float = 0.0, dolvol=1e8) -> Panel:
    r = np.full((T, n_names), ret)
    tri = np.cumprod(1.0 + r, axis=0)
    close = 100.0 * tri
    dv = (np.full((T, n_names), float(dolvol)) if np.isscalar(dolvol)
          else np.tile(np.asarray(dolvol, dtype=float), (T, 1)))
    return Panel(
        dates=np.array([f"d{i:04d}" for i in range(T)], dtype=object),
        permnos=np.arange(1, n_names + 1, dtype=np.int64),
        close=close.astype(np.float32), open_=close.astype(np.float32),
        ret=r.astype(np.float32), retx=r.astype(np.float32),
        traded=np.ones((T, n_names), dtype=bool),
        dolvol=dv.astype(np.float32),
        mktcap=np.full((T, n_names), 1e10, dtype=np.float32),
        tri=tri.astype(np.float32), source="flat")


# ------------------------------------------------- identity: nothing moved

def test_adding_curve_changed_NO_existing_policy_id():
    """The whole point of `_HASH_NEUTRAL_DEFAULTS`. These hashes were taken
    from the code BEFORE the field existed; a `policy_id` is what tells a
    receipt and a rerun they are the same policy, and a field appended to a
    frozen dataclass changes every one of them unless it is dropped at its
    default."""
    assert Policy().policy_id == "6479736fde09f076"
    assert Policy(signal="mom_12_1", holding_days=5,
                  top_k=10).policy_id == "a07f8af3442df626"
    assert Policy(transaction_cost_bps=0.0, slippage_bps=0.0,
                  zero_cost_diagnostic=True).policy_id == "394a47ae22f5a61d"
    assert Policy(sizing="inverse_vol", universe_n=1000,
                  note="x").policy_id == "4c3465df467616b1"


def test_a_REAL_ARCHIVED_row_still_reproduces_its_own_policy_id():
    """The strongest available pin: a row written by a 2013-2024 farm run,
    reconstructed field by field, must still hash to the identity the receipt
    on disk records. A literal in a test can be regenerated by accident; an
    archived receipt cannot."""
    d = (Path(__file__).resolve().parents[1] / "data" / "optimus"
         / "portfolio_farm")
    receipts = sorted(d.glob("farm_*_2013_2024.json")) if d.exists() else []
    if not receipts:                                     # pragma: no cover
        pytest.skip("archived farm receipts not on disk")
    fields = set(Policy.__dataclass_fields__)
    n = renamed = 0
    for p in receipts:
        blob = json.loads(p.read_text(encoding="utf-8"))
        for rows in blob.values():
            if not (isinstance(rows, list) and rows
                    and isinstance(rows[0], dict) and "policy_id" in rows[0]):
                continue
            for row in rows:
                kw = {k: v for k, v in row.items() if k in fields}
                if "curve" in kw:                        # pragma: no cover
                    continue
                try:
                    pol = Policy(**kw)
                except PolicyError:
                    # A row whose SIGNAL was renamed in Aug 2026 is already
                    # unreconstructable and has been since that rename -- a
                    # pre-existing fact this test surfaces rather than causes.
                    renamed += 1
                    continue
                assert pol.policy_id == row["policy_id"], (
                    f"{p.name}: {row['label']}")
                n += 1
    assert n >= 1000, f"only {n} archived rows reconstructed"
    assert renamed < n / 10, (
        f"{renamed} archived rows are unreconstructable because their signal "
        f"was renamed; that is a separate, pre-existing problem, but at this "
        f"share it would hollow out this pin")


def test_adding_curve_changed_NO_existing_strategy_fingerprint():
    assert _strategy().fingerprint == "7cb2b90871a82563"


def test_curve_IS_part_of_the_identity_at_any_other_value():
    """SPEC S4 ITEM 6. Two policies identical but for the curve are two
    policies -- a `curve='taq_empirical'` re-run of a promoted flat book is a
    NEW record, never a silent edit of the promoted one."""
    assert Policy().policy_id != Policy(curve="taq_empirical").policy_id
    assert (Policy(curve="taq_empirical").policy_id
            != Policy(curve="retail_paper").policy_id)
    assert (_strategy().fingerprint
            != _strategy(costs=CostModel(curve="taq_empirical")).fingerprint)


def test_a_field_appended_at_its_default_is_invisible_to_the_hash_ONLY_there():
    """The mechanism, asserted directly, so a future field added the wrong way
    fails here rather than silently re-identifying every archived book."""
    from backend.services.portfolio_farm.policy import _HASH_NEUTRAL_DEFAULTS
    # `decay` joined the record on 2026-09-12 (chunk 8, the decay-blended
    # target weights) by the SAME mechanism, and the four hashes above are the
    # proof it stayed invisible at its default.
    assert _HASH_NEUTRAL_DEFAULTS == {"curve": "flat", "decay": 0.0}
    assert Policy().curve == "flat"
    assert Policy().decay == 0.0
    assert CostModel().curve == "flat"
    assert CostModel().flat_bps is None


# ----------------------------------------------------------- the refusals

@pytest.mark.parametrize("curve", ["flat", "taq_empirical", "retail_paper"])
def test_zero_cost_still_REFUSES_under_every_curve(curve, monkeypatch):
    """SPEC S4 ITEM 4. The refusal asks whichever ruler is declared: under a
    curve the two flat fields are unused, so a curve whose every rate happened
    to floor at exactly zero is the bug this catches."""
    from backend.services import cost_curve as CC

    if curve == "flat":
        with pytest.raises(PolicyError, match="zero transaction cost"):
            Policy(transaction_cost_bps=0.0, slippage_bps=0.0)
    else:
        Policy(curve=curve)                     # the real floor is positive
        monkeypatch.setattr(CC, "curve_floor_one_way_bps", lambda _c: 0.0)
        with pytest.raises(PolicyError, match="zero transaction cost"):
            Policy(curve=curve, transaction_cost_bps=0.0, slippage_bps=0.0)


@pytest.mark.parametrize("curve", ["taq_empirical", "retail_paper"])
def test_a_frictionless_diagnostic_under_a_CURVE_is_two_contradictions(curve):
    with pytest.raises(PolicyError, match="contradictory"):
        Policy(curve=curve, transaction_cost_bps=0.0, slippage_bps=0.0,
               zero_cost_diagnostic=True)


def test_an_unknown_curve_is_refused_at_construction():
    with pytest.raises(PolicyError, match="unknown cost curve"):
        Policy(curve="free_lunch")
    with pytest.raises(PolicyError, match="unknown cost curve"):
        CostModel(curve="free_lunch")


def test_a_retail_book_graded_on_a_CRSP_replay_is_a_regime_mismatch():
    """SPEC S1.6. Retail fills see IEX quotes and a partial-fill process this
    engine does not simulate; pricing them off the SIP-wide tape would
    understate them by construction."""
    with pytest.raises(ValueError, match="REGIME MISMATCH"):
        replay.run(_panel(), Policy(top_k=5, universe_n=8,
                                    signal="oldest_listing",
                                    curve="retail_paper"), warmup=260)


# ------------------------------------------------------- the flat path held

def test_the_flat_path_is_UNCHANGED_to_the_cent():
    """The reserve/target refactor must be a no-op under `flat`, or every
    archived net silently stops reproducing. Same hand arithmetic as
    `test_a_flat_market_LOSES_exactly_the_costs`:
        deployed = 10,000 * (1 - 0.0012) = 9,988.00
        cost     = 9,988.00 * 0.0006     =     5.9928
    """
    res = replay.run(_panel(), Policy(top_k=5, universe_n=20,
                                      holding_days=1000,
                                      signal="oldest_listing"), warmup=260)
    assert res.nav[-1] == pytest.approx(10_000.0 - 5.9928, abs=1e-6)
    assert res.diagnostics["cost_curve"] == "flat"
    assert res.diagnostics["cost_curve_provenance"] == "flat_declared"
    assert res.diagnostics["mean_realised_cost_bps"] == pytest.approx(6.0)


# ------------------------------------------------------- the curve path runs

def test_the_curve_charges_PER_NAME_and_the_receipt_says_what_it_charged():
    dv = np.array([2e6, 5e6, 2e7, 5e7, 3e8, 9e8, 1e9, 4e9])
    res = replay.run(_panel(dolvol=dv),
                     Policy(top_k=8, universe_n=8, holding_days=1000,
                            signal="oldest_listing", curve="taq_empirical"),
                     warmup=260)
    d = res.diagnostics
    assert d["cost_curve"] == "taq_empirical"
    assert d["n_name_fills_priced_by_curve"] == 8
    assert d["n_name_fills_curve_unpriceable"] == 0
    assert d["curve_unpriceable_fraction"] == 0.0
    # The measured branch is structurally unreachable from a permno panel and
    # the receipt SAYS so rather than implying TAQ priced these fills.
    mix = d["cost_curve_provenance_mix"]
    assert mix["MEASURED_TAQ_EFFECTIVE"] == 0
    assert mix["EXTRAPOLATED_REGRESSION"] == 8
    # Spread and impact are reported APART: collapsing them is how the two
    # become one word three call sites later.
    assert d["cost_curve_spread_usd"] > 0
    assert d["cost_curve_impact_usd"] >= 0
    assert (d["cost_curve_spread_usd"] + d["cost_curve_impact_usd"]
            == pytest.approx(d["total_cost_usd"], abs=0.02))
    assert d["mean_realised_cost_bps"] > 0
    assert d["cost_ratio_curve_over_flat"] > 0


def test_the_illiquid_tercile_costs_MORE_than_the_liquid_one():
    """Not a tautology: it is the sign of `b1` surviving the whole pipeline
    from the fit, through the replay's per-fill lookup, onto a receipt."""
    dv = np.array([2e6, 3e6, 4e6, 5e6, 3e8, 5e8, 9e8, 4e9])
    res = replay.run(_panel(dolvol=dv),
                     Policy(top_k=8, universe_n=8, holding_days=1000,
                            signal="oldest_listing", curve="taq_empirical"),
                     warmup=260)
    terciles = res.diagnostics["cost_bps_by_liquidity_tercile"]
    assert terciles["under_10m"]["one_way_bps"] > terciles["over_100m"]["one_way_bps"]
    assert res.diagnostics["liquidity_tercile_cuts_usd"] == [1e7, 1e8]


def test_a_name_the_curve_cannot_price_is_charged_the_DECLARED_rate_and_counted():
    """And it is NOT charged an end of the declared band --
    `cost_model.resolve_band_by_picking` is a named refusal, and a loop is the
    last place to start quietly picking ends."""
    p = _panel(dolvol=np.array([1e8] * 8))
    # VOLATILITY is the input that can genuinely be absent here: a name with
    # no dollar volume is already ineligible (`eligible_at` requires a finite
    # trailing dolvol), so the only way into the unpriceable branch is a
    # missing sigma -- which is what a name with too little history has.
    vol = np.full((T, 8), 0.01)
    vol[:, :4] = np.nan
    res = replay.run(p, Policy(top_k=8, universe_n=8, holding_days=1000,
                               signal="oldest_listing", curve="taq_empirical"),
                     vol=vol, warmup=260)
    d = res.diagnostics
    assert d["n_name_fills_curve_unpriceable"] == 4
    assert d["curve_unpriceable_fraction"] == 0.5


def test_the_curve_rides_on_every_result_row():
    res = replay.run(_panel(), Policy(top_k=5, universe_n=20,
                                      holding_days=1000,
                                      signal="oldest_listing"), warmup=260)
    row = res.as_row()
    assert row["cost_curve"] == "flat"
    assert "mean_realised_cost_bps" in row
    assert "cost_curve_provenance" in row
    assert "cost_bps_by_liquidity_tercile" in row
    assert CostModel().as_row()["cost_curve"] == "flat"
    assert CostModel(curve="taq_empirical").as_row()["cost_curve"] == "taq_empirical"


def test_the_label_is_unchanged_under_flat_and_names_the_curve_otherwise():
    assert Policy().label.endswith("/12bp")
    assert Policy(curve="taq_empirical").label.endswith("/taq_empirical")


def test_across_phases_does_not_merge_two_curves_into_one_median():
    from backend.services.portfolio_farm.farm import across_phases
    from backend.services.portfolio_farm.policy import FarmResult

    def _r(curve, terminal):
        pol = Policy(top_k=5, universe_n=20, curve=curve)
        return FarmResult(policy=pol, dates=["d"], nav=[1.0],
                          metrics={"status": "ok", "terminal_usd": terminal},
                          diagnostics={})

    out = across_phases([_r("flat", 1.0), _r("taq_empirical", 2.0)])
    assert len(out) == 2, "two curves collapsed into one row"
    assert {r["cost_curve"] for r in out} == {"flat", "taq_empirical"}
