"""C1 -- the COUNTERFACTUAL NEWS CURRICULUM, generated by the local Qwen at $0.

    python -m scripts.night_c_counterfactual_news --max-docs 3        # plumbing
    python -m scripts.night_c_counterfactual_news --hours 7           # the night

WHAT THIS IS, AND THE ONE THING IT MUST NEVER BE
================================================
Murat's "made-up news" idea, kept on the right side of the line the 2026-09-08
roadmap draws: a real historical headline is anonymised (every company, person
and product becomes a placeholder, so a model cannot recall the outcome) and
the local model writes three CONTROLLED counterfactuals, each changing exactly
one causal element -- the sign (beat -> miss), the magnitude (x3), the actor or
the timing. Each carries the direction the change implies.

That is a CURRICULUM: it teaches a text model causal ordering and sentiment
sensitivity. The supervised labels for money are ALWAYS the market's own
returns on the REAL headline (via E0, the joined text-and-return panel). We
never tell a network "this invented story caused +8%"
that would teach it our
imagination. So this file writes NO return, NO price, NO outcome of any kind.

Priority order of documents: 2020-2024 first (those years have CRSP prices, so
their real headlines can be joined to returns later), then 2025-2026.
Resumable by uid
a receipt every 50 documents
the DeepSeek counterfactual
cost is printed so the $0 is a number, not a claim.

Backend: `local_gguf` (Qwen2.5-7B-Instruct-Q4_K_M on the laptop GPU through
`backend.services.free_inference`). The language pin and the >10% non-Latin
refusal apply centrally there
a refused reply is a row with a status, never a
retry. Telemetry rows are NOT written to llm_calls.jsonl (record=False) --
6,000 prompts of ~2 KB would bloat a tracked ledger
the counts live in the
receipt instead.
"""

from __future__ import annotations

import argparse
import glob
import hashlib
import json
import re
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from backend.services import free_inference as fi                      # noqa: E402
from backend.services.model_provider import LanguageRefused, ProviderRefusal  # noqa: E402

RUN_DATE = "2026-09-08"
OUT = REPO / "backend" / "data" / "optimus" / f"night_factory_{RUN_DATE}"
OUT.mkdir(parents=True, exist_ok=True)
ROWS = OUT / "C1_counterfactual_news.jsonl"
RECEIPT = OUT / "C1_counterfactual_news_receipt.json"
CORPUS = Path(r"C:\Users\mrthn\aegis-alpha-terminal\state\corpus\observations")
PRIORITY_YEARS = ("2020", "2021", "2022", "2023", "2024")
MAX_BODY = 1500

SYSTEM = ("You are a financial news editor building a training curriculum. Reply with ONE JSON "
          "object only, no prose before or after it. Write in English.")

EVENT_TYPES = ("EARNINGS", "GUIDANCE", "M&A", "FINANCING", "REGULATORY", "PRODUCT", "MANAGEMENT",
               "LEGAL", "MACRO", "ANALYST", "OTHER")
DIRECTIONS = ("POSITIVE", "NEGATIVE", "UNCLEAR")
MAGNITUDES = ("SMALL", "MEDIUM", "LARGE")
KINDS = ("sign_flip", "escalation", "actor_timing")

PROMPT = """Headline: {title}
Body: {body}

Do four things.
1. ANONYMISE: rewrite headline+body in 1-3 sentences with EVERY company, ticker, person, product and brand replaced by neutral placeholders (Company A, Company B, the CEO, the product, the regulator). Keep the numbers and the causal claim.
2. CLASSIFY the anonymised story for Company A: event_type in {event_types}
direction in {directions}
magnitude in {magnitudes}.
3. COUNTERFACTUALS: write three variants of the anonymised story, each changing EXACTLY ONE causal element, and state the change:
   - "sign_flip": the sign of the core fact reverses (beat->miss, approve->reject, buy->sell, rise->fall, hire->fire).
   - "escalation": the same fact, three times larger in magnitude.
   - "actor_timing": the same fact happens to a competitor instead, or is delayed by a year.
   Give the direction each variant implies for Company A.
4. Return exactly:
{{"anon": "...", "event_type": "...", "direction": "...", "magnitude": "...",
 "counterfactuals": [
  {{"kind": "sign_flip", "changed": "...", "text": "...", "direction": "..."}},
  {{"kind": "escalation", "changed": "...", "text": "...", "direction": "..."}},
  {{"kind": "actor_timing", "changed": "...", "text": "...", "direction": "..."}}]}}"""

_JSON = re.compile(r"\{.*\}", re.S)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _uid_order(uid: str) -> str:
    return hashlib.sha1(uid.encode()).hexdigest()


def load_docs():
    docs = []
    for f in sorted(glob.glob(str(CORPUS / "*.jsonl"))):
        with open(f, encoding="utf-8", errors="replace") as fh:
            for line in fh:
                try:
                    d = json.loads(line)
                except Exception:  # noqa: BLE001
                    continue
                if not d.get("body") or not d.get("symbols") or not d.get("uid") or d.get("kind") != "news":
                    continue
                docs.append({"uid": d["uid"], "effective_at": d.get("effective_at") or "",
                             "title": d.get("title") or "", "body": d["body"][:MAX_BODY],
                             "symbols": list(d["symbols"])[:8], "source": d.get("source")})
    docs.sort(key=lambda d: (0 if d["effective_at"][:4] in PRIORITY_YEARS else 1, _uid_order(d["uid"])))
    return docs


def anonymise_pre(text: str, symbols) -> str:
    for s in symbols:
        if s and len(s) >= 2:
            text = re.sub(rf"\b{re.escape(s)}\b", "TICK", text)
    return text


def parse(text: str) -> tuple[dict | None, str | None]:
    m = _JSON.search(text or "")
    if not m:
        return None, "REFUSED_UNPARSEABLE"
    try:
        obj = json.loads(m.group(0))
    except Exception:  # noqa: BLE001
        return None, "REFUSED_UNPARSEABLE"
    if not isinstance(obj, dict):
        return None, "REFUSED_UNPARSEABLE"
    et = str(obj.get("event_type", "")).upper()
    di = str(obj.get("direction", "")).upper()
    mg = str(obj.get("magnitude", "")).upper()
    cfs = obj.get("counterfactuals")
    if et not in EVENT_TYPES or di not in DIRECTIONS or mg not in MAGNITUDES or not isinstance(cfs, list):
        return None, "REFUSED_SCHEMA"
    clean = []
    for c in cfs:
        if not isinstance(c, dict):
            continue
        k = str(c.get("kind", "")).lower()
        d = str(c.get("direction", "")).upper()
        if k in KINDS and d in DIRECTIONS and c.get("text"):
            clean.append({"kind": k, "changed": str(c.get("changed", ""))[:300], "text": str(c["text"])[:900], "direction": d})
    if len(clean) < 2 or not obj.get("anon"):
        return None, "REFUSED_SCHEMA"
    return {"anon": str(obj["anon"])[:1200], "event_type": et, "direction": di, "magnitude": mg,
            "counterfactuals": clean}, None


def receipt(stats: dict, *, final: bool) -> None:
    wall = max(time.time() - stats["t0"], 1e-6)
    tin, tout = stats["tokens_in"], stats["tokens_out"]
    stats_out = {
        "job": "C1_counterfactual_news", "licence": "PRODUCT_EXPERIMENT",
        "what": "anonymised real headlines + three one-change counterfactuals each; NO returns, NO outcomes",
        "backend": stats["backend"], "model": stats.get("model"),
        "written_utc": _now(), "final": final,
        "docs_attempted": stats["n"], "docs_ok": stats["ok"], "refusals": stats["refusals"],
        "docs_per_hour": round(stats["n"] / wall * 3600, 1), "wall_s": round(wall, 1),
        "tokens_in": tin, "tokens_out": tout, "cost_usd": 0.0,
        "deepseek_counterfactual_usd": fi.counterfactual_deepseek(tin, tout) if hasattr(fi, "counterfactual_deepseek") else None,
        "by_year": stats["by_year"], "event_types": stats["event_types"], "directions": stats["directions"],
        "rows_file": str(ROWS),
        "headline": (f"{stats['ok']} curriculum rows ({stats['n']} attempted) at {round(stats['n'] / wall * 3600)} docs/hr, "
                     f"$0.00; refusals {stats['refusals']}"),
        "verdict": "DATASET (curriculum), not a result. Feeds the text arm of the NN lane once E0 joins returns.",
        "family_max_p": None,
    }
    RECEIPT.write_text(json.dumps(stats_out, indent=1), encoding="utf-8")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--hours", type=float, default=7.0)
    ap.add_argument("--max-docs", type=int, default=None)
    ap.add_argument("--backend", default="local_gguf")
    ap.add_argument("--max-tokens", type=int, default=700)
    a = ap.parse_args(argv)
    docs = load_docs()
    done = set()
    if ROWS.exists():
        for line in ROWS.open(encoding="utf-8"):
            try:
                done.add(json.loads(line)["uid"])
            except Exception:  # noqa: BLE001
                pass
    todo = [d for d in docs if d["uid"] not in done]
    print(f"C1: {len(docs):,} candidate docs, {len(done):,} already done, {len(todo):,} to do; "
          f"priority years first {PRIORITY_YEARS}", flush=True)
    stats = {"t0": time.time(), "n": 0, "ok": 0, "refusals": {}, "tokens_in": 0, "tokens_out": 0,
             "backend": a.backend, "model": None, "by_year": {}, "event_types": {}, "directions": {}}
    t_end = time.time() + a.hours * 3600
    with ROWS.open("a", encoding="utf-8") as out:
        for d in todo:
            if time.time() > t_end or (OUT / "STOP").exists():
                break
            if a.max_docs and stats["n"] >= a.max_docs:
                break
            title = anonymise_pre(d["title"], d["symbols"])
            body = anonymise_pre(d["body"], d["symbols"])
            prompt = PROMPT.format(title=title, body=body, event_types="/".join(EVENT_TYPES),
                                   directions="/".join(DIRECTIONS), magnitudes="/".join(MAGNITUDES))
            row = {"uid": d["uid"], "effective_at": d["effective_at"], "symbols": d["symbols"],
                   "source": d["source"], "backend": a.backend, "utc": _now()}
            t0 = time.monotonic()
            try:
                rep = fi.complete(a.backend, prompt, system=SYSTEM, max_tokens=a.max_tokens,
                                  temperature=0.7, purpose="counterfactual_news", record=False, timeout=180)
                stats["model"] = rep.model
                stats["tokens_in"] += rep.tokens_in
                stats["tokens_out"] += rep.tokens_out
                obj, refusal = parse(rep.text)
                row.update({"latency_s": rep.latency_s, "tokens_in": rep.tokens_in, "tokens_out": rep.tokens_out})
                if refusal:
                    row["status"] = refusal
                    row["raw_head"] = (rep.text or "")[:200]
                else:
                    row["status"] = "OK"
                    row.update(obj)
            except LanguageRefused as exc:
                row["status"] = "REFUSED_LANGUAGE"
                row["why"] = str(exc)[:200]
                r = getattr(exc, "reply", None)
                if r is not None:
                    stats["tokens_in"] += int(r.tokens_in or 0)
                    stats["tokens_out"] += int(r.tokens_out or 0)
            except ProviderRefusal as exc:
                row["status"] = "REFUSED_PROVIDER"
                row["why"] = str(exc)[:300]
                # a dead server ends the night rather than writing 6,000 refusals
                out.write(json.dumps(row) + "\n")
                out.flush()
                stats["n"] += 1
                stats["refusals"]["REFUSED_PROVIDER"] = stats["refusals"].get("REFUSED_PROVIDER", 0) + 1
                if stats["refusals"]["REFUSED_PROVIDER"] >= 5:
                    print(f"C1: five provider refusals in a row -- ending: {exc}", flush=True)
                    break
                time.sleep(20)
                continue
            row.setdefault("latency_s", round(time.monotonic() - t0, 3))
            out.write(json.dumps(row) + "\n")
            out.flush()
            stats["n"] += 1
            if row["status"] == "OK":
                stats["ok"] += 1
                y = d["effective_at"][:4]
                stats["by_year"][y] = stats["by_year"].get(y, 0) + 1
                stats["event_types"][row["event_type"]] = stats["event_types"].get(row["event_type"], 0) + 1
                stats["directions"][row["direction"]] = stats["directions"].get(row["direction"], 0) + 1
            else:
                stats["refusals"][row["status"]] = stats["refusals"].get(row["status"], 0) + 1
            if stats["n"] % 50 == 0:
                receipt(stats, final=False)
                print(f"    {stats['n']} docs, {stats['ok']} ok, {round(stats['n'] / max(time.time() - stats['t0'], 1) * 3600)} docs/hr", flush=True)
    receipt(stats, final=True)
    print(f"C1 done: {stats['ok']} ok of {stats['n']} -> {ROWS}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
